### ISSUE TITLE
Not installable from Git

### ISSUE THREAD

**Issue by owais** [indexiatech/redux-immutablejs#13]
`lib/index.js` does not exist in the git repo. Should it be shipped so people can install the package directly from github? It is very useful for testing PRs or testing latest versions in general.

**Comment by asaf** [comment]
I dislike the concept of having build files inside the source repo,
You can always fork it, run build:lib and commit the `lib` folder for your own use though

**Comment by asaf** [comment]
Closing, if you still want to discuss this feel free to reopen :)

**Comment by owais** [comment]
I've "vendored" in the PR I need for now so don't need it right away but it is a nice thing to have. A necessary evil :)
