### ISSUE TITLE
Can not work with redux-router

### ISSUE THREAD

**Issue by clinyong** [indexiatech/redux-immutablejs#19]
reducers.js
```js
import { combineReducers } from 'redux-immutablejs';
...
export const rootReducer = combineReducers({
  router: routerStateReducer,
  ...
});
```

configureStore.js

```js
...
const initialState = rootReducer(Immutable.fromJS({}));
const logger = createLogger();
const finalCreateStore = compose(
    applyMiddleware(thunk, api, logger),
    reduxReactRouter({
        routes,
        createHistory
    })
)(createStore);

export default function configureStore(initialState) {
  return finalCreateStore(rootReducer, initialState);
};
```

There is something wrong, and the console in Chrome says

```
Uncaught TypeError: Cannot read property 'type' of undefined
```

Where `type` in

```js
function routerStateReducer(state, action) {
  if (state === undefined) state = null;

  var _extends2;

  switch (action.type) { // error 
    case _constants.ROUTER_DID_CHANGE:
      return action.payload;
    case _constants.REPLACE_ROUTES:
      if (!state) return state;
      return _extends({}, state, (_extends2 = {}, _extends2[_constants.DOES_NEED_REFRESH] = true, _extends2));
    default:
      return state;
  }
}
```

I follow the example in README, but it did not work. I'm new to redux, could you tell me how to fix it.

**Comment by fgarcia** [comment]
The problem is that most code expects **state.router** to exist, however the new combineReducers you are using causes **state** to be a Map() which breaks access to **state.router**

You might just go back to the standard combine function or wrap the main reducer to inject the "router" attribute into the returned state

**Comment by clinyong** [comment]
Thanks @fgarcia. But if I use the standard combine function, how to make state immutable. Could you give me some code?

**Comment by fgarcia** [comment]
I've just upgraded back to full Immutable state, so keep using the immutable combine and do this:

    // DEFAULT const routerStateSelector = state => state.router;
    const routerStateSelector = state => state.get('router');
    //  ...
    reduxReactRouter({ routes, createHistory, routerStateSelector })

**Comment by clinyong** [comment]
@fgarcia , I try your solution, like below

```js
import { createStore, compose, applyMiddleware } from 'redux'
import { reduxReactRouter } from 'redux-router'
import createHistory from 'history/lib/createBrowserHistory'
import routes from './routes'
import { rootReducer } from './reducers'                                                                                                                                    import thunk from 'redux-thunk'
import Immutable from 'immutable'

const state = Immutable.fromJS({})
const initialState = rootReducer(state)
const routerStateSelector = state => state.get('router')

const finalCreateStore = compose(
  applyMiddleware(thunk),
  reduxReactRouter({
    routerStateSelector,
    routes,
    createHistory
  })
)(createStore)

export default function configureStore () {
  return finalCreateStore(rootReducer, initialState)
}
```

But it still not works...I debug in  the `routerStateReducer.js` file

```js
function routerStateReducer(state, action) {
  if (state === undefined) state = null;

  var _extends2;

  console.log(action);  // add this

  switch (action.type) {
    case _constants.ROUTER_DID_CHANGE:
      return action.payload;
    case _constants.REPLACE_ROUTES:
      if (!state) return state;
      return _extends({}, state, (_extends2 = {}, _extends2[_constants.DOES_NEED_REFRESH] = true, _extends2));
    default:
      return state;
  }
}

...
```

And the console prints

```
Object {type: "INIT"}
Object {type: "8.8.l.3.j.0.m.g.q.f.r"}
undefined
```

**Comment by neverfox** [comment]
It should be `state => state.get('router').toJS()`. redux-router needs a POJO.

**Comment by fgarcia** [comment]
@neverfox only **state** is an ImmutableJS object, in my code the result of get already returns a POJO and I am already using this package combine function. Maybe is it different for the OP?

**Comment by neverfox** [comment]
Ah, I see. I had assumed that redux-immutablejs did a fromJS recursively. I don't use this library personally because I don't really see the advantage of making the top level state layer immutable (mainly because it breaks plugins like redux-router and redux-forms, without adding much benefit that I can see). I prefer to just apply ImmutableJS to the *values* of my top level state keys (in my custom reducers' initialState).

**Comment by clinyong** [comment]
@neverfox `state => state.get('router').toJS()` is not the right way... The `action` still be **undefined**.

This library seems too complicated for me, and I decide to use ImmutableJS just in reducers as @neverfox  said.

Thanks guys.

**Comment by neverfox** [comment]
@clinyong I just took at stab at it by looking at the source code. @fgarcia is right that, at the very least, it doesn't need `toJS()` but since it wasn't working for you even without that, I'm at a loss.
