### ISSUE TITLE
Is this still needed?

### ISSUE THREAD

**Issue by rclai** [indexiatech/redux-immutablejs#22]
According to redux-immutable:

As of Redux@3+, you don't need to use redux-immutable to use Immutable.js. See http://stackoverflow.com/a/31899857/368691.

**Comment by ansonkao** [comment]
@rclai what was your conclusion? Is redux-immatablejs indeed obsolete with Redux 3+?

**Comment by rclai** [comment]
It is not obsolete, this is only needed for a specific Immutable use case.

I was able to get Immutable to work in Redux without it.
