### ISSUE TITLE
redux-immutablejs + redux-devtools no longer showing state

### ISSUE THREAD

**Issue by eventhough** [indexiatech/redux-immutablejs#5]
When I implemented this library and converted my entire state object into a single immutable, [redux-devtools](https://github.com/gaearon/redux-devtools) stopped displaying the current state. Has anyone seen this issue? I figured I would ask here first since this is very specific to redux-immutablejs.

**Comment by asaf** [comment]
I haven't tested redux-devtools yet but from this first look it doesn't seems to support Immutables.

**Comment by gaearon** [comment]
Redux DevTools supports Immutables but [there was a bug](https://github.com/gaearon/redux-devtools/issues/88#issuecomment-138204548) in `react-json-tree` that prevented them from rendering.

Please try `redux-devtools@2.1.1` to see if it fixes the issue.

**Comment by asaf** [comment]
@gaearon Thanks for clarifying this.
